name: Update Sitemaps
on:
  push:
    branches:
      - workflow-actions
    paths:
      - 'github-actions-test/scrapper/**'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install dependencies
        run : npm install

      - name: Run script
        run: node webscraper.io\ cloud\ api/rest-scripts/scape-job.script.js
