name: Update Sitemaps
on:
  push:
    branches:
      - main
    paths:
      - "scrapper/**"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if scrapper directory exists
        run: |
          if [ ! -d "scrapper" ]; then
            echo "Scrapper directory not found. Exiting workflow."
            exit 1
          fi

      - name: install dependencies
        run: npm install

      - name: Run script
        run: node scripts/scrape-job.script.js
